services:
  file-handler:
    container_name: file-handler
    build:
      context: filehandler
      dockerfile: ../Dockerfile
    restart: always
    environment:
      - TASK_QUEUE_URL=http://task-queue:8080
      - TASK_HANDLER_URL=http://task-handler:8080
    ports:
      - "8081:8080"
    volumes:
      - ./:/tmp:cached
    depends_on: [ task-queue, task-handler ]

  task-queue:
    container_name: task-queue
    build:
      context: taskqueue
      dockerfile: ../Dockerfile
    restart: always
    ports:
      - "8082:8080"
    depends_on: [task-handler]

  task-handler:
    container_name: task-handler
    build:
      context: taskhandler
      dockerfile: ../Dockerfile
    restart: always
    ports:
      - "8083:8080"
